### PR TITLE
[Feature] Swift Package Manager (SPM) Integration

### PR DESCRIPTION
**Pull request by fila95**
**Why**
This PR is needed to provide Swift Package Manager compatibility for Tempura

**Changes**
- Added Package.swift
- Moved `TempuraTesting` related sources to an outer folder
- Updated Cakefile and Podfile for TempuraTesting
- Updated README.md and Changelog

**Tasks**
* [x] Add relevant tests, if needed
* [x] Add documentation, if needed
* [x] Update README, if needed
* [x] Ensure that the demo project works properly

### CODE REVIEW

**Comment by MicheleMola** [comment]
Hi, when do you merge this branch? Thank you.

**Review by LorDisturbia — APPROVED** [review]

**Comment by danyf90** [comment]
Note that adding this will hit the limitations of SPM versioning in which a tag defines the versions for all the libraries which are part of the Package, and hence Tempura and TempuraTesting will need to be ALWAYS released together if they remain in the same repository.

That said, I don't think it is a great problem, but then we should unify the version on CocoaPods, too (hence removing the `.version-tempura` and `.version-tempura-elements` files in favor of a single `.version` file)

cc @LorDisturbia

**Review by danyf90 — CHANGES_REQUESTED** [review]
Note that adding this will hit the limitations of SPM versioning in which a tag defines the versions for all the libraries which are part of the Package, and hence Tempura and TempuraTesting will need to be ALWAYS released together if they remain in the same repository.

This would mean that if we want to do a major of TempuraTesting, we should release the same also for Tempura, and viceversa.

cc @LorDisturbia

**Comment by LorDisturbia** [comment]
I wouldn't support it for now, because keeping the versions aligned might be a problem.
IMHO, we can reevaluate this if and once we drop Cocoapods. What do you think @fila95?

**Comment by fila95** [comment]
> I wouldn't support it for now, because keeping the versions aligned might be a problem.
> IMHO, we can reevaluate this if and once we drop Cocoapods. What do you think @fila95?

:ci-sta: let's reevaluate later on

**Pull request closed without merging**
