### PR TITLE
[Fix] Katana Dispatch Helpers

### PR DESCRIPTION
**Pull request by fila95**
**Why**
This PR fixes an issue for which Apps dispatching `NavigationSideEffects` relied on Tempura's duplicate interface instead of Katana ones.
It also deprecates a potentially insecure and UI Locking helper to await a Promise dispatch on ViewControllers.

**Changes**
- Deprecated all `dispatch` helpers to `AnyStore` and `AnySideEffectContext` for `NavigationSideEffect`s
- Deprecated `__unsafeAwaitDispatch ` from `ViewController` for `NavigationSideEffect`s
- Added `__unsafeDispatch ` for non-returning sideeffects in `ViewController`

**Tasks**
* [x] Add relevant tests, if needed
* [x] Add documentation, if needed
* [x] Update README, if needed
* [x] Ensure that the demo project works properly

### CODE REVIEW

**Comment by bolismauro** [comment]
This change is breaking, can't we just deprecate them?
Finally, @FEC-bendingspoons can't we also remove 
```swift
public func __unsafeDispatch<RSE: NavigationSideEffect>(_ dispatchable: RSE) -> Promise<Void>
```
it shouldn't be necessary anymore

**Review by FEC-bendingspoons — APPROVED** [review]
LGTM, but I agree with Mauro: I'll deprecate the method you removed so that the change is not breaking and we can release a minor.

**Comment by fila95** [comment]
> This change is breaking, can't we just deprecate them?
> Finally, @FEC-bendingspoons can't we also remove
> 
> ```swift
> public func __unsafeDispatch<RSE: NavigationSideEffect>(_ dispatchable: RSE) -> Promise<Void>
> ```
> 
> it shouldn't be necessary anymore

Problem about removing it is that `NavigationSideEffect` is that it inherits directly from `AnySideEffect` and not `SideEffect`. Without this `__unsafeDispatch` you can't at the moment trigger a `Show` operation in VCs.
Do we want to remove it anyway? @bolismauro @FEC-bendingspoons

**Review by smaramba — APPROVED** [review]

**Comment by smaramba** [comment]
Good to me, @FEC-bendingspoons can you please take care of updating the CHANGELOG and releasing this?

**Pull request merged**
