### PR TITLE
Misc fixes for Travis build and Swift 4.0 warnings...

### PR DESCRIPTION
**Pull request by cajurabi**
**Why**
The latest release has numerous warnings on Swift 4.0.  Those include protocol inheritance issues which should have used protocol composition to resolve.   In addition, the flatMap use was deprecated  in SDK 9.3.  Lastly the travis build was not working.  

**Changes**
Implemented protocol composition to resolve redundant associatedtype declarations.
Changed flatMap to compactMap where appropriate.
Instead of custom travis.yml for performing tests, switched to fastlane.
Removed Podfile dependency listings since the project provides a Podfile.lock.
Fixed README.md which was pointing to Katana instead of Tempura build.
Bumped Pod version number to 1.1.13 -- may want to move to v 2.0 since this does break SDK 9.2 and lower support.  Unfortunately there is no compile time check for SDK version in Swift.  Boo Swift...

**Tasks**
* [ ] Need to decide on proper version number.
* [ ] Support for Katana 1.1.11

### CODE REVIEW

**Comment by cajurabi** [comment]
I have had the build error once before during testing.  Appears to be a caching issue with Tempura project file.  My subsequent builds pass, see here: https://travis-ci.org/cajurabi/tempura-swift/builds/407458611

Recommend you trigger a rebuild to see if it resolves.

**Comment by cajurabi** [comment]
Very strange.  I suspect your Travis-CI has special settings which is leading to this issue.  The build works in my branch.  See:

https://travis-ci.org/cajurabi/tempura-swift/builds/407461806

**Comment by cajurabi** [comment]
@abignoli I'm out of ideas as to what is broken in your Travis environment.  All of these builds work in my Travis-CI.  Recommend you open a ticket with Travis-CI to review why the build fails for your account but works in mine.  The very nature of Travis-CI is it is a reproducible build env.  It should not work in mine and fail in yours.

**Comment by cajurabi** [comment]
FYI, just got it to fail in my Travis build.  I will continue to troubleshoot.  Maybe an issue with Fastlane or with the project file itself.

**Comment by cajurabi** [comment]
@smaramba turns out the testing on Travis is fragile.  A restart of build will fix a failure.  I suspect the issue is that the tests are assigned to the same scheme as the pod scheme--Tempura.  If the tests were attached to the TempuraTesting instead of Tempura that make fix the flakiness.

**Comment by smaramba** [comment]
Hey there @cajurabi thanks for taking the time to contribute and sorry for the late response.
Could you please split the changes in two separate PRs, one for the warnings and one for the CI (I can confirm that the issue is that tests are assigned to the same scheme as the pod scheme--Tempura).
So that we can merge/release them in different moments?
thanks

**Comment by smaramba** [comment]
Closing as everything is addressed in `Tempura 2.0`.

**Pull request closed without merging**
